---
  - name: get CDH repository package
    get_url: url=https://archive.cloudera.com/cdh5/one-click-install/redhat/7/x86_64/cloudera-cdh-5-0.x86_64.rpm dest=~/cloudera-cdh-5-0.x86_64.rpm
  - name: Install CDH repository package
    shell: yum --nogpgcheck localinstall ~/cloudera-cdh-5-0.x86_64.rpm
  - name: get ClouderaManager repo list
    get_url: url=http://archive.cloudera.com/cm4/debian/squeeze/amd64/cm/cloudera.list dest=/etc/apt/sources.list.d/cloudera-manager.list
  - name: update the repositories
    shell: apt-get update